name: Pages with SQLite Database

on:
  push:
    branches: [master]
    paths:
      - 'data/**.json' # JSON data changes
      - 'src/**' # Vue components
      - 'public/**' # Public assets
      - '*.html' # HTML files
      - '*.js' # JavaScript files
      - '*.css' # CSS files
      - 'package*.json' # Dependencies
      - 'vite.config.js' # Vite config
      - 'tailwind.config.js' # Tailwind config
      - 'postcss.config.js' # PostCSS config
      - '.github/workflows/**.yml' # Workflow changes
      - '.github/workflows/**.yaml' # Alternative YAML extension
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Python dependencies
        run: |
          uv sync

      - name: Install Node dependencies
        run: |
          npm ci

      - name: Generate SQLite database
        run: |
          uv run cubscrape build-db

      - name: Verify database creation
        run: |
          ls -la data/
          file data/games.db

      - name: Build Vue application
        run: |
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
