name: Pages with SQLite Database

on:
  push:
    branches: [ master ]
    paths:
      - 'data/**.json'  # Only trigger on JSON data changes
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: Install dependencies
      run: |
        uv sync
    
    - name: Generate SQLite database
      run: |
        uv run python scraper/scraper.py build-db
    
    - name: Verify database creation
      run: |
        ls -la data/
        file data/games.db
    
    - name: Prepare deployment directory
      run: |
        mkdir -p deploy/data
        cp index.html deploy/
        cp script.js deploy/
        cp style.css deploy/
        cp config.json deploy/
        cp data/games.db deploy/data/
        ls -la deploy/
        ls -la deploy/data/
    
    - name: Setup Pages
      uses: actions/configure-pages@v5
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: 'deploy'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5